development:
  adapter: postgresql
  encoding: unicode
  database: marathon_stats_development
  pool: 5
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>

test:
  adapter: postgresql
  encoding: unicode
  database: marathon_stats_test
  pool: 5
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
